import TimeSlotRow from "./TimeSlotRow";
import { useState, useRef, useEffect } from "react";
import { Loader2, CheckCircle, XCircle, Clock } from "lucide-react";
import { usePlanner } from "../../context/PlannerContext";
import { useSavePriorityTasks } from "../../api calls/daily_tasks_api";

// ─── DUMMY DATA ───────────────────────────────────────────────
// Replace values with real API data when endpoint is ready.
// Keys must match the time labels generated by generateTimeSlots().
const DUMMY_PLANNED = {
  "05:00 AM": "Morning walk & stretching",
  "06:00 AM": "Read 20 pages",
  "07:00 AM": "Breakfast + review day plan",
  // group: Deep work block (3 consecutive slots, same label)
  "09:00 AM": "Deep work – feature development",
  "10:00 AM": "Deep work – feature development",
  "11:00 AM": "Deep work – feature development",
  "12:00 PM": "Lunch break",
  "02:00 PM": "Team standup meeting",
  // group: Code review block (2 consecutive slots, same label)
  "03:00 PM": "Code review & PR feedback",
  "04:00 PM": "Code review & PR feedback",
  "07:00 PM": "Gym",
  "09:00 PM": "Personal project",
  "11:00 PM": "Wind down – reading",
};

const DUMMY_ACTUAL = {
  "05:00 AM": "Morning walk done ✓",
  "06:00 AM": "Read 15 pages",
  "07:00 AM": "Skipped breakfast, just reviewed plan",
  "09:00 AM": "Worked on auth module",
  "10:00 AM": "Finished auth + started dashboard",
  "12:00 PM": "Lunch + short nap",
};
// ─────────────────────────────────────────────────────────────

// Parse "HH:MM AM/PM" label → 24h integer for comparison
const parseSlotHour24 = (timeLabel) => {
  const [timePart, meridiem] = timeLabel.split(" ");
  let [h] = timePart.split(":").map(Number);
  if (meridiem === "PM" && h !== 12) h += 12;
  if (meridiem === "AM" && h === 12) h = 0;
  return h;
};

// Returns the current IST hour (0–23)
const getCurrentISTHour = () => {
  const now = new Date();
  const istOffset = 5.5 * 60 * 60 * 1000;
  const ist = new Date(now.getTime() + istOffset);
  return ist.getUTCHours();
};

export default function TimeSlotPlanner() {
  const { timeTasks, updateTimeTask } = usePlanner();
  const { saveTracker } = useSavePriorityTasks();
  const scrollRef = useRef(null);
  const currentRowRef = useRef(null);

  const [saveState, setSaveState] = useState({
    status: "idle",
    message: ""
  });

  // Merge dummy data into timeTasks values for display
  // TODO: remove DUMMY_PLANNED / DUMMY_ACTUAL once real API hydrates timeTasks
  const slots = timeTasks?.values.map(slot => ({
    ...slot,
    planned: slot.planned || DUMMY_PLANNED[slot.time] || "",
    actual: slot.actual || DUMMY_ACTUAL[slot.time] || "",
  }));

  const currentHour = getCurrentISTHour();

  // Find index of current time slot
  const currentIndex = slots?.findIndex(slot => {
    const slotHour = parseSlotHour24(slot.time);
    // Slots run 5AM–2AM (next day). Treat post-midnight slots (0,1,2) as hour 24,25,26
    const normalizedSlot = slotHour < 5 ? slotHour + 24 : slotHour;
    const normalizedCurrent = currentHour < 5 ? currentHour + 24 : currentHour;
    return normalizedSlot === normalizedCurrent;
  });

  // Compute group position for consecutive slots with identical planned text
  const getGroupPosition = (i) => {
    const val = slots[i].planned.trim();
    if (!val) return null;
    const prev = i > 0 && slots[i - 1].planned.trim() === val;
    const next = i < slots.length - 1 && slots[i + 1].planned.trim() === val;
    if (prev && next) return "middle";
    if (prev) return "last";
    if (next) return "first";
    return null;
  };

  // Auto-scroll to current slot on mount
  useEffect(() => {
    if (currentRowRef.current && scrollRef.current) {
      const container = scrollRef.current;
      const row = currentRowRef.current;
      const offset = row.offsetTop - container.offsetTop - 16;
      container.scrollTo({ top: offset, behavior: "smooth" });
    }
  }, [slots?.length]);

  const handleSaveTimeSlots = async () => {
    setSaveState({ status: "loading", message: "Saving time slots to Excel..." });
    const result = await saveTracker(timeTasks);

    if (result?.status >= 200 && result?.status < 300) {
      setSaveState({ status: "success", message: "Time slots saved successfully" });
    } else {
      setSaveState({ status: "error", message: "Failed to save time slots" });
    }

    setTimeout(() => setSaveState({ status: "idle", message: "" }), 3000);
  };

  return (
    <div className="bg-blue-100 border border-blue-300 rounded-2xl p-4 shadow-sm">
      <div className="flex justify-between items-center mb-3">
        <h3 className="flex items-center gap-2 font-semibold text-gray-700 text-sm">
          <Clock size={18} />
          Time-Based Planner (5 AM – 2 AM)
        </h3>

        <button
          onClick={handleSaveTimeSlots}
          disabled={saveState.status === "loading"}
          className={`text-xs px-4 py-1.5 rounded-full flex items-center gap-1
            ${saveState.status === "loading"
              ? "bg-gray-400 cursor-not-allowed text-white"
              : "bg-indigo-500 hover:bg-indigo-600 text-white"
            }`}
        >
          {saveState.status === "loading" && <Loader2 size={14} className="animate-spin" />}
          Save
        </button>
      </div>

      {/* Save Notification */}
      {saveState.status !== "idle" && (
        <div className={`mb-3 flex items-center gap-2 text-xs px-3 py-2 rounded-xl
          ${saveState.status === "success" && "bg-green-100 text-green-700"}
          ${saveState.status === "error" && "bg-red-100 text-red-700"}
          ${saveState.status === "loading" && "bg-blue-100 text-blue-700"}
        `}>
          {saveState.status === "loading" && <Loader2 size={14} className="animate-spin" />}
          {saveState.status === "success" && <CheckCircle size={14} />}
          {saveState.status === "error" && <XCircle size={14} />}
          <span>{saveState.message}</span>
        </div>
      )}

      {/* Time Slots */}
      <div ref={scrollRef} className="max-h-[420px] overflow-y-auto pr-1 pretty-scroll">
        {slots?.map((slot, i) => {
          const isCurrent = i === currentIndex;
          const isFilled = !!slot.planned.trim();
          const groupPosition = getGroupPosition(i);
          const noBottomGap = groupPosition === "first" || groupPosition === "middle";
          return (
            <div
              key={slot.time}
              ref={isCurrent ? currentRowRef : null}
              className={noBottomGap ? "mb-px" : "mb-2"}
            >
              <TimeSlotRow
                time={slot.time}
                planned={slot.planned}
                actual={slot.actual}
                isCurrent={isCurrent}
                isFilled={isFilled}
                groupPosition={groupPosition}
                onPlannedChange={text => updateTimeTask(i, "planned", text)}
                onActualChange={text => updateTimeTask(i, "actual", text)}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}
